### ISSUE TITLE
Load more articles does not scroll up

### ISSUE THREAD

**Issue by Aprillion** [kentcdodds/remix-kentcdodds#123]
While clicking on "Load more articles" button in https://kent.dev/blog actually loads more articles, if I already scrolled beyond the previous ones, it will display the new ones above my current position on the screen. See screenshot (after clicking the button), Firefox 92 on MacOS:

<img width="1679" alt="Screenshot 2021-09-22 at 16 34 41" src="https://user-images.githubusercontent.com/1087670/134364081-2c324c75-fd7f-44e1-b7c5-866b0e9cae18.png">

Would be more noticeable if the new loaded articles became visible on the screen.

**Comment by kentcdodds** [comment]
I'm not sure what to do about this because it's actually how the browser works. If you're scroll position includes the area of the DOM that's modified then it will leave your clientTop untouched. If you're scroll position does not include the area of the DOM that's modified, then it will keep the DOM visible where you are.

I tend to prefer to not change what the browser does like this so I think I'll leave this as-is. Thanks!

**Comment by smeijer** [comment]
Can the button be placed in the part that's being modified?

**Comment by kentcdodds** [comment]
Tried. Doesn't work 🤷‍♂️

**Comment by Aprillion** [comment]
oh well ¯\_(ツ)_/¯
