### ISSUE TITLE
Implement sitemap.xml

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/remix-kentcdodds#39]
Inspiration: https://gist.github.com/andrelandgraf/0112631dcdf6640e4bd44360d3e7a08e

**Comment by kentcdodds** [comment]
This is done

**Comment by O-Q** [comment]
Are there any benefits for separating the sitemap route from others in [`other-routes.server.ts`](https://github.com/kentcdodds/kentcdodds.com/blob/main/app/other-routes.server.ts) instead of the [`[sitemap.xml]`](https://remix.run/docs/en/v1/api/conventions#escaping-special-characters) file with loader?

**Comment by kentcdodds** [comment]
Yeah, I need the remixContext object for what I'm doing. Hopefully eventually we'll be able to expose that in another way because this really should bea resource route.
