### ISSUE TITLE
add permlink to frontmatter?

### ISSUE THREAD

**Issue by smeijer** [kentcdodds/remix-kentcdodds#53]
Copy buttons need a full URL to be copied to the clipboard. 

I can construct something using `new URL(frontmatter.slug, location.origin).toString()`, but this will not work server-side. 

My proposal; add a `BASE_URL` env var, and use that to construct perma-links that will be part of the frontmatter.

**Comment by kentcdodds** [comment]
Was about to write this but then decided to just make it work anyway and it's not all that bad. Here's what I was going to write:

We can't use `BASE_URL` as a global env variable because we don't know for sure what the domain URL will be. We could just hard code it to `kent.dev`, but then when we move over to `kentcdodds.com` or if I ever do deploy previews all the links will be wrong. That's why I created:

https://github.com/kentcdodds/remix-kentcdodds/blob/930308323f4c0182b5ca57d14a7d9a27f54b1cc0/app/utils/misc.tsx#L162-L170

We use that to put the `origin` in the `requestInfo` in our root route:

https://github.com/kentcdodds/remix-kentcdodds/blob/930308323f4c0182b5ca57d14a7d9a27f54b1cc0/app/root.tsx#L103-L107

Then that's put into context:

https://github.com/kentcdodds/remix-kentcdodds/blob/930308323f4c0182b5ca57d14a7d9a27f54b1cc0/app/root.tsx#L176

And we use that to create things like the discord authorization URL: https://github.com/kentcdodds/remix-kentcdodds/blob/adb6eb3ff59b4678a65b49547dc6aceffa897249/app/routes/me.tsx#L80

So we could do the same for permalinks.

I tried adding a `permalink` property to the `MdxPage` type, but that just made things much more complicated because we had to pass the request object (or at least the `origin` everywhere we created `MdxPage` objects) ... hold up. Let me try a different approach... Yeah, that's not all that bad. `MdxPage` now has a `permalink` property.

**Comment by kentcdodds** [comment]
Actually, I changed my mind again. We don't need the permalink all that often, so I think I'd prefer to just construct it wherever we need it:

```tsx
const requestInfo = useRequestInfo()
const permalink = `${requestInfo.origin}/blog/${page.slug}`
```

**Comment by smeijer** [comment]
`useRequestInfo().origin` looks great! Let's use that.
